### ISSUE TITLE
need working version of createuptodateregister in python

### ISSUE THREAD

**Issue by Joesalmon1985** [Joesalmon1985/Canvas#20]
We need a working version of createuptodateregister in python

https://github.com/Joesalmon1985/Canvas/blob/master/createuptodateregister.sql

This creates a table with all the addtions added and deletions taken out.

**Comment by Ben-green** [comment]
I have made you a starter. Take a look at my repository.

**Comment by Joesalmon1985** [comment]
This is to ambitious at the moment.

**Comment by Ben-green** [comment]
Concerning 141201, yes you might need to be in the right directory.
