### ISSUE TITLE
t_add_postcode_column.py needs explaining text

### ISSUE THREAD

**Issue by Joesalmon1985** [Joesalmon1985/Canvas#25]
I would find it very handy to understand what t_*.py programs do.

**Comment by Ben-green** [comment]
See http://pylonsbook.com/en/1.1/testing.html#introducing-nose and http://stackoverflow.com/questions/3371255/writing-unit-tests-in-python-how-do-i-start .

**Comment by Joesalmon1985** [comment]
Okay I think I'm there with this now
