### ISSUE TITLE
Scripts need to be less fussy over column headings 

### ISSUE THREAD

**Issue by Joesalmon1985** [Joesalmon1985/Canvas#35]
Currently freshdata.py and councilupdate.py only work with specific file headings for the CSV files they use, down to the correct character. This could be improved massively, maybe with something smart enough to recognise what type of data is in each column i.e. a name, an address, an intention.

**Comment by Ben-green** [comment]
I am taking a look at your failing tests

**Comment by Ben-green** [comment]
I have pushed my work. Let me know if I am on the right lines.
Where are the scripts being too fussy?

**Comment by Joesalmon1985** [comment]
There needs to be a way for us to establish what type of data is under each
column heading. Imagine we cannot get people to rename the columns
firstname or first_name instead of First Name, and so forth.

My bet would be we write a script that looks at the first 7 or 8 rows of a
column, and then decides if that data is address data, names, voting
intention and the like, and treats the data accordingly.

I'm away on holiday with Kate with no electric and infrequent internet
access (in coffee shop atm) so feel I can't really elaborate as much as I
should to make what I'm on about clear, so no worries if you can't progress
without more useful feedback from me.

Stay cool dude

**Comment by Joesalmon1985** [comment]
Okay, I think this is a bit unnecessary at the moment, as we can just tell users to change column settings.

Maybe look at this if it becomes a problem down the line.
